name: CI/CD Pipeline

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
env:
    PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

jobs:
    build:
        strategy:
            matrix:
                node-version: [18.x]

        name: Build with ${{ matrix.node-version }}
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Install Yarn
              run: npm install -g yarn
            - name: Install dependencies
              run: yarn
            - name: Build
              run: yarn build
    test:
        strategy:
            matrix:
                node-version: [18.x]

        name: Run E2E, Unit Test, Build Story book
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Retrieve Git history, needed to verify commits
            - name: Use Node.Js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Install Yarn
              run: npm install -g yarn
            - name: Install dependencies
              run: yarn
            - name: Build
              run: yarn build

            - if: github.event_name == 'pull_request'
              name: Validate all commits from PR
              run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

            - name: Linter
              run: yarn lint

            - name: Type checking
              run: yarn check-types

            - name: Run unit tests
              run: yarn test

            - name: Run storybook tests
              run: yarn build-storybook

            - name: Run e2e tests
              run: npx percy exec -- npm run e2e:headless
